keys:
  - &hasty-desktop age1ch924fqpeaqgzum68878ka6gumcsg8j5lplggyp7flx0zkyh9f2sjjj6s2
  - &hastyshell age1xyp24nt94qj8w8uezpll24egyej5l9a9ccl6r5atd7fd4asmgpqqhp4wa6

creation_rules:
  - path_regex: hosts/nixos/hasty-desktop/secrets\.yaml$
    key_groups:
      - age:
          - *hasty-desktop
          - *hastyshell
